SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

-- Создаём таблицу Users
CREATE TABLE IF NOT EXISTS "Users" (
  "Id" INT GENERATED BY DEFAULT AS IDENTITY,
  "FirstName" text NOT NULL,
  "SecondName" text NOT NULL,
  "Email" text NOT NULL,
  "Password" text NOT NULL,
  CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

-- Создаём таблицу RefreshToken
CREATE TABLE IF NOT EXISTS "RefreshToken" (
    "Id" INTEGER NOT NULL,
    "Token" TEXT NOT NULL
);
