SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

-- Создаём таблицу Users
CREATE TABLE IF NOT EXISTS public."Users" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "FirstName" TEXT NOT NULL,
    "SecondName" TEXT NOT NULL,
    "Email" TEXT NOT NULL,
    "Password" TEXT NOT NULL
);

